"""Contact detection and response utilities."""

from .broad_phase import UniformTriangleAABBHash, triangle_aabbs
from .backends import ContactBackendResult, PenaltyContactBackend
from .field_contact import (
    FieldContactConstraint,
    FieldContactMatrixFreeStiffness,
    FieldSurfaceContactResponse,
    SurfaceQuadratureCache,
    assemble_field_contact_jacobian,
    compute_field_contact_constraints,
    field_contact_constraint_from_sample,
    field_contact_jacobian_entries,
    field_contact_jacobian_row,
    field_penalty_contact_response,
    node_to_surface_field_penalty_response,
    quadrilateral_master_surface_penalty_response,
    quadrilateral_surface_quadrature_cache,
    surface_to_surface_field_penalty_response,
    surface_to_surface_field_penalty_response_vectorized,
    triangle_surface_quadrature_cache,
    triangle_surface_quadrature_samples,
)
from .constraint_region import (
    active_constraint_region_tangent_data_from_arrays,
    aggregate_contact_sample_arrays,
    contact_active_region_continuity_metrics_from_arrays,
    constraint_region_gap_jacobian_sparse_from_arrays,
    constraint_region_contact_tangent_sparse_from_arrays,
    constraint_region_pressure_tangent_scales_from_arrays,
    constraint_region_reduced_contact_tangent_sparse_from_arrays,
    constraint_region_reduced_gap_jacobian_sparse_from_arrays,
    constraint_region_tangent_metrics_from_arrays,
    contact_averaging_modes,
    contact_path_tracking_metrics_from_arrays,
    contact_region_integral_metrics_from_arrays,
    secondary_node_pressure_recovery_from_regions,
)
from .hard_contact import (
    HardContactSolution,
    hard_contact_gap_jacobian_from_samples,
    solve_linear_hard_contact_active_set,
    solve_linear_hard_contact_from_samples,
)
from .tracking_state import (
    accepted_contact_response_can_reuse,
    commit_accepted_contact_tracking_from_sample_arrays,
    restore_contact_tracking_state,
    run_contact_tracking_trial,
    snapshot_contact_tracking_state,
)
from .jacobian import (
    assemble_contact_jacobian,
    contact_jacobian_entries,
    contact_jacobian_row,
)
from .lagrangian_sdf_oracle import (
    LagrangianOracleConstraint,
    LagrangianOracleContactResponse,
    LagrangianPatchPairQueryResult,
    LagrangianPullbackQueryResult,
    LagrangianSDFContactOracle,
    LagrangianSDFQueryResult,
    lagrangian_oracle_constraint_from_sample,
    lagrangian_oracle_jacobian_row,
    lagrangian_oracle_penalty_response,
    lagrangian_oracle_penalty_response_batch,
    lagrangian_patch_pair_query,
)
from .lagrangian_surface_contact import LagrangianSDFSurfaceContactGeometry
from .narrow_phase import (
    ContactConstraint,
    SurfaceSample,
    compute_contact_constraints,
    contact_constraint_from_sample,
)
from .penalty import penalty_contact_response
from .sdf_geometry import DynamicSurfaceSDFContactGeometry

__all__ = [
    "ContactConstraint",
    "ContactBackendResult",
    "DynamicSurfaceSDFContactGeometry",
    "FieldContactConstraint",
    "FieldContactMatrixFreeStiffness",
    "FieldSurfaceContactResponse",
    "HardContactSolution",
    "LagrangianOracleConstraint",
    "LagrangianOracleContactResponse",
    "LagrangianPatchPairQueryResult",
    "LagrangianPullbackQueryResult",
    "LagrangianSDFContactOracle",
    "LagrangianSDFSurfaceContactGeometry",
    "LagrangianSDFQueryResult",
    "SurfaceQuadratureCache",
    "PenaltyContactBackend",
    "SurfaceSample",
    "UniformTriangleAABBHash",
    "active_constraint_region_tangent_data_from_arrays",
    "accepted_contact_response_can_reuse",
    "assemble_contact_jacobian",
    "assemble_field_contact_jacobian",
    "aggregate_contact_sample_arrays",
    "compute_contact_constraints",
    "compute_field_contact_constraints",
    "commit_accepted_contact_tracking_from_sample_arrays",
    "contact_active_region_continuity_metrics_from_arrays",
    "constraint_region_contact_tangent_sparse_from_arrays",
    "constraint_region_gap_jacobian_sparse_from_arrays",
    "constraint_region_pressure_tangent_scales_from_arrays",
    "constraint_region_reduced_contact_tangent_sparse_from_arrays",
    "constraint_region_reduced_gap_jacobian_sparse_from_arrays",
    "constraint_region_tangent_metrics_from_arrays",
    "contact_constraint_from_sample",
    "contact_averaging_modes",
    "contact_jacobian_entries",
    "contact_jacobian_row",
    "contact_path_tracking_metrics_from_arrays",
    "contact_region_integral_metrics_from_arrays",
    "field_contact_constraint_from_sample",
    "field_contact_jacobian_entries",
    "field_contact_jacobian_row",
    "field_penalty_contact_response",
    "hard_contact_gap_jacobian_from_samples",
    "lagrangian_oracle_constraint_from_sample",
    "lagrangian_oracle_jacobian_row",
    "lagrangian_oracle_penalty_response",
    "lagrangian_oracle_penalty_response_batch",
    "lagrangian_patch_pair_query",
    "node_to_surface_field_penalty_response",
    "penalty_contact_response",
    "quadrilateral_master_surface_penalty_response",
    "quadrilateral_surface_quadrature_cache",
    "restore_contact_tracking_state",
    "run_contact_tracking_trial",
    "secondary_node_pressure_recovery_from_regions",
    "solve_linear_hard_contact_active_set",
    "solve_linear_hard_contact_from_samples",
    "snapshot_contact_tracking_state",
    "surface_to_surface_field_penalty_response",
    "surface_to_surface_field_penalty_response_vectorized",
    "triangle_aabbs",
    "triangle_surface_quadrature_cache",
    "triangle_surface_quadrature_samples",
]
