"""Finite-element kernels for the standalone solver."""

from .assembler import (
    assemble_gravity_force,
    assemble_mass_matrix,
    assemble_stiffness_matrix,
)
from .body import DeformableBody
from .calculix_aligned import (
    ContactGeometry,
    ContactResponse,
    ContactSample,
    InternalResponse,
    MechanicsModel,
    MechanicsState,
    PlaneContactGeometry,
    StaticForceState,
    StepDiagnostics,
    assemble_calculix_c3d4_mass,
    assemble_consistent_mass,
    assemble_contact_response,
    calculix_apply_acceleration_increment,
    calculix_dynamic_predictor,
    calculix_hht_effective_residual,
    calculix_hht_effective_tangent,
    evaluate_state,
    hht_newmark_parameters,
    hht_step,
    initial_state,
    static_force_state,
    static_residual_and_tangent,
    stvk_internal_response,
)
from .constraints import (
    eliminate_fixed_dofs,
    fixed_dofs_from_node_set,
    free_dofs,
    project_fixed_dofs,
)
from .integrator import newmark_beta_step
from .material import isotropic_linear_elasticity_matrix
from .tet4 import (
    tet4_consistent_mass,
    tet4_lumped_mass,
    tet4_mass,
    tet4_shape_function_gradients,
    tet4_strain_displacement_matrix,
    tet4_stiffness,
    tet4_volume,
)

__all__ = [
    "DeformableBody",
    "ContactGeometry",
    "ContactResponse",
    "ContactSample",
    "InternalResponse",
    "MechanicsModel",
    "MechanicsState",
    "PlaneContactGeometry",
    "StaticForceState",
    "StepDiagnostics",
    "assemble_calculix_c3d4_mass",
    "assemble_consistent_mass",
    "assemble_gravity_force",
    "assemble_contact_response",
    "calculix_apply_acceleration_increment",
    "calculix_dynamic_predictor",
    "calculix_hht_effective_residual",
    "calculix_hht_effective_tangent",
    "assemble_mass_matrix",
    "assemble_stiffness_matrix",
    "evaluate_state",
    "eliminate_fixed_dofs",
    "fixed_dofs_from_node_set",
    "free_dofs",
    "hht_newmark_parameters",
    "hht_step",
    "initial_state",
    "newmark_beta_step",
    "project_fixed_dofs",
    "isotropic_linear_elasticity_matrix",
    "static_force_state",
    "static_residual_and_tangent",
    "stvk_internal_response",
    "tet4_consistent_mass",
    "tet4_lumped_mass",
    "tet4_mass",
    "tet4_shape_function_gradients",
    "tet4_strain_displacement_matrix",
    "tet4_stiffness",
    "tet4_volume",
]
