"""Finite-element kernels for the standalone solver."""

from .assembler import (
    assemble_gravity_force,
    assemble_mass_matrix,
    assemble_stiffness_matrix,
)
from .body import DeformableBody
from .calculix_aligned import (
    ContactGeometry,
    ContactResponse,
    ContactSample,
    InternalResponse,
    MechanicsModel,
    MechanicsState,
    PlaneContactGeometry,
    StaticForceState,
    StepDiagnostics,
    assemble_calculix_c3d4_mass,
    assemble_consistent_mass,
    assemble_contact_response,
    assemble_hex8_mass,
    calculix_apply_acceleration_increment,
    calculix_dynamic_predictor,
    calculix_hht_effective_residual,
    calculix_hht_effective_tangent,
    evaluate_state,
    hht_newmark_parameters,
    hht_step,
    initial_state,
    static_force_state,
    static_residual_and_tangent,
    stvk_internal_response,
    hex8_reference_data,
)
from .constraints import (
    eliminate_fixed_dofs,
    fixed_dofs_from_node_set,
    free_dofs,
    project_fixed_dofs,
)
from .deformation_map import DeformationMapEvaluation, FEMDeformationMap
from .elements import (
    C3D8_HEX8_BACKEND,
    C3D4_TET4_BACKEND,
    ElementBackend,
    available_element_backends,
    canonical_fem_element_type,
    get_element_backend,
    register_element_backend,
)
from .hex8 import (
    C3D8_NATURAL_NODE_COORDS,
    HEX8_CENTER_NATURAL_GRADIENTS,
    hex8_center_strain_stress,
    hex8_consistent_mass,
    hex8_lumped_mass,
    hex8_mass,
    hex8_natural_gradients,
    hex8_shape_functions,
    hex8_stiffness,
    hex8_strain_displacement_matrix,
    hex8_volume,
)
from .integrator import newmark_beta_step
from .implicit_dirichlet import hht_step_dirichlet, initial_state_dirichlet
from .material import isotropic_linear_elasticity_matrix
from .rp_mpc import (
    FiniteRotationRigidHubMPC,
    RigidHubMPC,
    constant_torque_rotation_history,
    merge_dirichlet_conditions,
    reduced_hub_rotational_inertia,
    rotation_matrix_from_vector,
)
from .tet4 import (
    tet4_consistent_mass,
    tet4_lumped_mass,
    tet4_mass,
    tet4_shape_function_gradients,
    tet4_strain_displacement_matrix,
    tet4_stiffness,
    tet4_volume,
)

__all__ = [
    "DeformableBody",
    "DeformationMapEvaluation",
    "FEMDeformationMap",
    "ContactGeometry",
    "ContactResponse",
    "ContactSample",
    "InternalResponse",
    "MechanicsModel",
    "MechanicsState",
    "PlaneContactGeometry",
    "StaticForceState",
    "StepDiagnostics",
    "assemble_calculix_c3d4_mass",
    "assemble_consistent_mass",
    "assemble_hex8_mass",
    "assemble_gravity_force",
    "assemble_contact_response",
    "calculix_apply_acceleration_increment",
    "calculix_dynamic_predictor",
    "calculix_hht_effective_residual",
    "calculix_hht_effective_tangent",
    "assemble_mass_matrix",
    "assemble_stiffness_matrix",
    "evaluate_state",
    "eliminate_fixed_dofs",
    "fixed_dofs_from_node_set",
    "free_dofs",
    "C3D4_TET4_BACKEND",
    "C3D8_HEX8_BACKEND",
    "ElementBackend",
    "available_element_backends",
    "canonical_fem_element_type",
    "get_element_backend",
    "hht_newmark_parameters",
    "hht_step",
    "hht_step_dirichlet",
    "hex8_reference_data",
    "C3D8_NATURAL_NODE_COORDS",
    "HEX8_CENTER_NATURAL_GRADIENTS",
    "hex8_center_strain_stress",
    "hex8_consistent_mass",
    "hex8_lumped_mass",
    "hex8_mass",
    "hex8_natural_gradients",
    "hex8_shape_functions",
    "hex8_stiffness",
    "hex8_strain_displacement_matrix",
    "hex8_volume",
    "initial_state",
    "initial_state_dirichlet",
    "newmark_beta_step",
    "project_fixed_dofs",
    "FiniteRotationRigidHubMPC",
    "RigidHubMPC",
    "constant_torque_rotation_history",
    "register_element_backend",
    "merge_dirichlet_conditions",
    "reduced_hub_rotational_inertia",
    "rotation_matrix_from_vector",
    "isotropic_linear_elasticity_matrix",
    "static_force_state",
    "static_residual_and_tangent",
    "stvk_internal_response",
    "tet4_consistent_mass",
    "tet4_lumped_mass",
    "tet4_mass",
    "tet4_shape_function_gradients",
    "tet4_strain_displacement_matrix",
    "tet4_stiffness",
    "tet4_volume",
]
