"""Plane-contact versus dynamic-SDF contact equivalence diagnostics.

This validation script answers one specific question: when the master surface is
just the finite triangulated plane used by the CalculiX-aligned block-drop case,
does replacing the analytic plane gap with the dynamic FEM-induced SDF query
change the contact samples?

It deliberately does not call CalculiX.  The state trajectory is generated by
the current SFC CalculiX-aligned rigid-plane contact mode, then replayed through
both the analytic plane query and the dynamic-SDF plane query at the same nodal
configurations.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from sfc.contact import UniformTriangleAABBHash  # noqa: E402
from validation.calculix_f2f_contact import (  # noqa: E402
    CalculixC3D4FaceToFacePlaneContactGeometry,
    CalculixC3D4FaceToFaceSDFContactGeometry,
    PersistentCalculixC3D4FaceToFacePlaneContactGeometry,
    PersistentCalculixC3D4FaceToFaceSDFContactGeometry,
    CalculixF2FContactSpring,
)
from validation.run_calculix_drop_impact_comparison import _contact_plane_z  # noqa: E402
from validation.run_geometric_nonlinear_contact_validation import (  # noqa: E402
    _contact_model,
    _rigid_plane_master_surface,
    _sdf_plane_padding,
    run_sfc_geometric_contact_history,
)

Row = dict[str, Any]


def _write_csv(path: Path, rows: list[Row], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _spring_key(spring: CalculixF2FContactSpring) -> tuple[int, int]:
    return int(spring.slave_face_index), int(spring.slave_quadrature_index)


def _spring_force(spring: CalculixF2FContactSpring, stiffness: float) -> float:
    return float(stiffness) * float(spring.spring_area) * max(-float(spring.clearance), 0.0)


def _spring_energy(spring: CalculixF2FContactSpring, stiffness: float) -> float:
    penetration = max(-float(spring.clearance), 0.0)
    return 0.5 * float(stiffness) * float(spring.spring_area) * penetration * penetration


def _projection(spring: CalculixF2FContactSpring) -> np.ndarray:
    if spring.master_projection is None:
        return np.full(3, np.nan, dtype=float)
    return np.asarray(spring.master_projection, dtype=float)


def _spring_row(
    *,
    time: float,
    plane: CalculixF2FContactSpring,
    sdf: CalculixF2FContactSpring | None,
    stiffness: float,
) -> Row:
    plane_projection = _projection(plane)
    if sdf is None:
        return {
            "time": float(time),
            "slave_face_index": int(plane.slave_face_index),
            "slave_quadrature_index": int(plane.slave_quadrature_index),
            "sdf_found": "false",
            "plane_gap": float(plane.clearance),
            "sdf_gap": "",
            "gap_abs_error": "",
            "plane_force": _spring_force(plane, stiffness),
            "sdf_force": "",
            "force_abs_error": "",
            "plane_energy": _spring_energy(plane, stiffness),
            "sdf_energy": "",
            "energy_abs_error": "",
            "plane_active": str(plane.active).lower(),
            "sdf_active": "",
            "active_mismatch": "true",
            "normal_l2_error": "",
            "projection_l2_error": "",
            "spring_area_abs_error": "",
            "sdf_master_face_index": "",
            "sdf_master_weight_min": "",
            "sdf_master_weight_max": "",
            "plane_projection_x": plane_projection[0],
            "plane_projection_y": plane_projection[1],
            "plane_projection_z": plane_projection[2],
            "sdf_projection_x": "",
            "sdf_projection_y": "",
            "sdf_projection_z": "",
            "plane_normal_x": float(plane.normal[0]),
            "plane_normal_y": float(plane.normal[1]),
            "plane_normal_z": float(plane.normal[2]),
            "sdf_normal_x": "",
            "sdf_normal_y": "",
            "sdf_normal_z": "",
        }

    sdf_projection = _projection(sdf)
    plane_force = _spring_force(plane, stiffness)
    sdf_force = _spring_force(sdf, stiffness)
    plane_energy = _spring_energy(plane, stiffness)
    sdf_energy = _spring_energy(sdf, stiffness)
    normal_error = float(np.linalg.norm(np.asarray(plane.normal, dtype=float) - np.asarray(sdf.normal, dtype=float)))
    projection_error = float(np.linalg.norm(plane_projection - sdf_projection))
    master_weights = np.asarray(sdf.master_weights, dtype=float)
    return {
        "time": float(time),
        "slave_face_index": int(plane.slave_face_index),
        "slave_quadrature_index": int(plane.slave_quadrature_index),
        "sdf_found": "true",
        "plane_gap": float(plane.clearance),
        "sdf_gap": float(sdf.clearance),
        "gap_abs_error": abs(float(plane.clearance) - float(sdf.clearance)),
        "plane_force": plane_force,
        "sdf_force": sdf_force,
        "force_abs_error": abs(plane_force - sdf_force),
        "plane_energy": plane_energy,
        "sdf_energy": sdf_energy,
        "energy_abs_error": abs(plane_energy - sdf_energy),
        "plane_active": str(plane.active).lower(),
        "sdf_active": str(sdf.active).lower(),
        "active_mismatch": str(bool(plane.active != sdf.active)).lower(),
        "normal_l2_error": normal_error,
        "projection_l2_error": projection_error,
        "spring_area_abs_error": abs(float(plane.spring_area) - float(sdf.spring_area)),
        "sdf_master_face_index": int(sdf.master_face_index),
        "sdf_master_weight_min": "" if master_weights.size == 0 else float(np.min(master_weights)),
        "sdf_master_weight_max": "" if master_weights.size == 0 else float(np.max(master_weights)),
        "plane_projection_x": plane_projection[0],
        "plane_projection_y": plane_projection[1],
        "plane_projection_z": plane_projection[2],
        "sdf_projection_x": sdf_projection[0],
        "sdf_projection_y": sdf_projection[1],
        "sdf_projection_z": sdf_projection[2],
        "plane_normal_x": float(plane.normal[0]),
        "plane_normal_y": float(plane.normal[1]),
        "plane_normal_z": float(plane.normal[2]),
        "sdf_normal_x": float(sdf.normal[0]),
        "sdf_normal_y": float(sdf.normal[1]),
        "sdf_normal_z": float(sdf.normal[2]),
    }


def _summary_row(time: float, rows: list[Row], *, comparison: str) -> Row:
    def values(name: str) -> list[float]:
        return [float(row[name]) for row in rows if row.get(name) not in ("", None)]

    active_mismatches = [row for row in rows if row["active_mismatch"] == "true"]
    missing = [row for row in rows if row["sdf_found"] == "false"]
    max_gap = max(values("gap_abs_error") or [0.0])
    max_normal = max(values("normal_l2_error") or [0.0])
    max_projection = max(values("projection_l2_error") or [0.0])
    max_force = max(values("force_abs_error") or [0.0])
    max_area = max(values("spring_area_abs_error") or [0.0])
    status = "pass"
    if missing or active_mismatches:
        status = "fail"
    elif max_gap > 1.0e-10 or max_normal > 1.0e-10 or max_projection > 1.0e-10 or max_force > 1.0e-8:
        status = "check"
    return {
        "comparison": comparison,
        "time": float(time),
        "sample_count": len(rows),
        "missing_sdf_sample_count": len(missing),
        "active_mismatch_count": len(active_mismatches),
        "max_gap_abs_error": max_gap,
        "max_normal_l2_error": max_normal,
        "max_projection_l2_error": max_projection,
        "max_force_abs_error": max_force,
        "max_energy_abs_error": max(values("energy_abs_error") or [0.0]),
        "max_spring_area_abs_error": max_area,
        "plane_active_count": sum(1 for row in rows if row["plane_active"] == "true"),
        "sdf_active_count": sum(1 for row in rows if row["sdf_active"] == "true"),
        "plane_force_sum": float(sum(float(row["plane_force"]) for row in rows if row.get("plane_force") not in ("", None))),
        "sdf_force_sum": float(sum(float(row["sdf_force"]) for row in rows if row.get("sdf_force") not in ("", None))),
        "status": status,
    }


def _stateless_geometries(model: Any) -> tuple[CalculixC3D4FaceToFacePlaneContactGeometry, CalculixC3D4FaceToFaceSDFContactGeometry]:
    master_x, master_faces = _rigid_plane_master_surface(model)
    delta_safe = _sdf_plane_padding(model)
    broad_phase = UniformTriangleAABBHash.from_surface(
        master_x,
        master_faces,
        delta_safe=delta_safe,
        cell_size=max(0.25, delta_safe),
    )
    plane = CalculixC3D4FaceToFacePlaneContactGeometry(
        model.surface_faces,
        plane_z=_contact_plane_z(model),
        stiffness=model.contact_stiffness,
        quadrature="calculix_7",
        contact_element_weight=1,
    )
    sdf = CalculixC3D4FaceToFaceSDFContactGeometry(
        model.surface_faces,
        master_x,
        master_faces,
        candidate_provider=broad_phase.query_point,
        stiffness=model.contact_stiffness,
        master_element_node_count=4,
        quadrature="calculix_7",
        contact_element_weight=1,
    )
    return plane, sdf


def _persistent_geometries(
    model: Any,
) -> tuple[PersistentCalculixC3D4FaceToFacePlaneContactGeometry, PersistentCalculixC3D4FaceToFaceSDFContactGeometry]:
    master_x, master_faces = _rigid_plane_master_surface(model)
    delta_safe = _sdf_plane_padding(model)
    broad_phase = UniformTriangleAABBHash.from_surface(
        master_x,
        master_faces,
        delta_safe=delta_safe,
        cell_size=max(0.25, delta_safe),
    )
    plane = PersistentCalculixC3D4FaceToFacePlaneContactGeometry(
        model.surface_faces,
        plane_z=_contact_plane_z(model),
        stiffness=model.contact_stiffness,
        quadrature="calculix_7",
        release_tolerance_scale=1.0e-3,
        contact_element_weight=1,
        freeze_first_newton_iteration=False,
    )
    sdf = PersistentCalculixC3D4FaceToFaceSDFContactGeometry(
        model.surface_faces,
        master_x,
        master_faces,
        candidate_provider=broad_phase.query_point,
        stiffness=model.contact_stiffness,
        master_element_node_count=4,
        quadrature="calculix_7",
        release_tolerance_scale=1.0e-3,
        contact_element_weight=1,
        freeze_first_newton_iteration=False,
    )
    return plane, sdf


def _compare_springs(
    *,
    time: float,
    plane_springs: list[CalculixF2FContactSpring],
    sdf_springs: list[CalculixF2FContactSpring],
    stiffness: float,
) -> list[Row]:
    sdf_by_key = {_spring_key(spring): spring for spring in sdf_springs}
    rows: list[Row] = []
    for plane in plane_springs:
        rows.append(_spring_row(time=time, plane=plane, sdf=sdf_by_key.get(_spring_key(plane)), stiffness=stiffness))
    return rows


def run_diagnostic(
    out_dir: Path,
    *,
    duration: float = 0.08,
    dt: float = 0.001,
    resolution: int = 1,
    initial_velocity_z: float = -2.0,
    stride: int = 1,
) -> dict[str, Path]:
    """Run plane-vs-SDF equivalence diagnostics for the block-drop case."""

    model = _contact_model(
        resolution=int(resolution),
        duration=float(duration),
        dt=float(dt),
        case="block_drop",
        initial_velocity_z=float(initial_velocity_z),
    )
    snapshots: list[tuple[float, np.ndarray, np.ndarray, np.ndarray]] = []
    run_sfc_geometric_contact_history(
        model,
        contact_mode="persistent_calculix_c3d4_f2f",
        cutback_policy="calculix_direct",
        state_snapshots=snapshots,
    )
    snapshots = snapshots[:: max(1, int(stride))]

    stateless_plane, stateless_sdf = _stateless_geometries(model)
    persistent_plane, persistent_sdf = _persistent_geometries(model)

    stateless_rows: list[Row] = []
    persistent_rows: list[Row] = []
    summary_rows: list[Row] = []
    for time, x_current, _v, _a in snapshots:
        plane_springs = stateless_plane.contact_springs(x_current)
        sdf_springs = stateless_sdf.contact_springs(x_current)
        rows = _compare_springs(
            time=float(time),
            plane_springs=plane_springs,
            sdf_springs=sdf_springs,
            stiffness=model.contact_stiffness,
        )
        stateless_rows.extend(rows)
        summary_rows.append(_summary_row(float(time), rows, comparison="stateless_query"))

        persistent_plane.begin_increment(x_current)
        persistent_sdf.begin_increment(x_current)
        persistent_plane.begin_newton_iteration(2)
        persistent_sdf.begin_newton_iteration(2)
        plane_persistent_springs = persistent_plane.contact_springs(x_current)
        sdf_persistent_springs = persistent_sdf.contact_springs(x_current)
        rows = _compare_springs(
            time=float(time),
            plane_springs=plane_persistent_springs,
            sdf_springs=sdf_persistent_springs,
            stiffness=model.contact_stiffness,
        )
        persistent_rows.extend(rows)
        summary_rows.append(_summary_row(float(time), rows, comparison="persistent_lifecycle"))

    out_dir.mkdir(parents=True, exist_ok=True)
    detail_fields = [
        "time",
        "slave_face_index",
        "slave_quadrature_index",
        "sdf_found",
        "plane_gap",
        "sdf_gap",
        "gap_abs_error",
        "plane_force",
        "sdf_force",
        "force_abs_error",
        "plane_energy",
        "sdf_energy",
        "energy_abs_error",
        "plane_active",
        "sdf_active",
        "active_mismatch",
        "normal_l2_error",
        "projection_l2_error",
        "spring_area_abs_error",
        "sdf_master_face_index",
        "sdf_master_weight_min",
        "sdf_master_weight_max",
        "plane_projection_x",
        "plane_projection_y",
        "plane_projection_z",
        "sdf_projection_x",
        "sdf_projection_y",
        "sdf_projection_z",
        "plane_normal_x",
        "plane_normal_y",
        "plane_normal_z",
        "sdf_normal_x",
        "sdf_normal_y",
        "sdf_normal_z",
    ]
    summary_fields = [
        "comparison",
        "time",
        "sample_count",
        "missing_sdf_sample_count",
        "active_mismatch_count",
        "max_gap_abs_error",
        "max_normal_l2_error",
        "max_projection_l2_error",
        "max_force_abs_error",
        "max_energy_abs_error",
        "max_spring_area_abs_error",
        "plane_active_count",
        "sdf_active_count",
        "plane_force_sum",
        "sdf_force_sum",
        "status",
    ]
    stateless_path = out_dir / "sdf_plane_stateless_query_equivalence.csv"
    persistent_path = out_dir / "sdf_plane_persistent_lifecycle_equivalence.csv"
    summary_path = out_dir / "sdf_plane_equivalence_summary.csv"
    markdown_path = out_dir / "sdf_plane_equivalence_summary.md"
    _write_csv(stateless_path, stateless_rows, detail_fields)
    _write_csv(persistent_path, persistent_rows, detail_fields)
    _write_csv(summary_path, summary_rows, summary_fields)
    _write_markdown(
        markdown_path,
        model=model,
        duration=duration,
        dt=dt,
        resolution=resolution,
        initial_velocity_z=initial_velocity_z,
        stride=stride,
        summary_rows=summary_rows,
    )
    return {
        "stateless": stateless_path,
        "persistent": persistent_path,
        "summary": summary_path,
        "markdown": markdown_path,
    }


def _format_float(value: Any) -> str:
    try:
        return f"{float(value):.6e}"
    except (TypeError, ValueError):
        return str(value)


def _write_markdown(
    path: Path,
    *,
    model: Any,
    duration: float,
    dt: float,
    resolution: int,
    initial_velocity_z: float,
    stride: int,
    summary_rows: list[Row],
) -> None:
    worst = {
        "max_gap_abs_error": max(float(row["max_gap_abs_error"]) for row in summary_rows),
        "max_normal_l2_error": max(float(row["max_normal_l2_error"]) for row in summary_rows),
        "max_projection_l2_error": max(float(row["max_projection_l2_error"]) for row in summary_rows),
        "max_force_abs_error": max(float(row["max_force_abs_error"]) for row in summary_rows),
        "active_mismatch_count": max(int(row["active_mismatch_count"]) for row in summary_rows),
        "missing_sdf_sample_count": max(int(row["missing_sdf_sample_count"]) for row in summary_rows),
    }
    overall = "pass"
    if worst["active_mismatch_count"] or worst["missing_sdf_sample_count"]:
        overall = "fail"
    elif (
        worst["max_gap_abs_error"] > 1.0e-10
        or worst["max_normal_l2_error"] > 1.0e-10
        or worst["max_projection_l2_error"] > 1.0e-10
        or worst["max_force_abs_error"] > 1.0e-8
    ):
        overall = "check"

    lines = [
        "# SDF Plane Equivalence Diagnostic",
        "",
        "This diagnostic compares the analytic rigid-plane contact query against the dynamic FEM-induced SDF query at identical block-drop states.",
        "",
        "## Command",
        "",
        "```bash",
        (
            "python validation/run_sdf_plane_equivalence_diagnostic.py "
            f"--duration {duration:g} --dt {dt:g} --resolution {int(resolution)} "
            f"--initial-velocity-z {initial_velocity_z:g} --stride {int(stride)} --out-dir {path.parent.as_posix()}"
        ),
        "```",
        "",
        "## Model",
        "",
        f"- case: block_drop",
        f"- nodes: {model.nodes.shape[0]}",
        f"- tet elements: {model.tet_elements.shape[0]}",
        f"- boundary faces: {model.surface_faces.shape[0]}",
        f"- contact plane z: {_format_float(_contact_plane_z(model))}",
        f"- contact stiffness: {_format_float(model.contact_stiffness)}",
        "",
        "## Worst Metrics",
        "",
        f"- overall status: `{overall}`",
        f"- max gap absolute error: `{_format_float(worst['max_gap_abs_error'])}`",
        f"- max normal L2 error: `{_format_float(worst['max_normal_l2_error'])}`",
        f"- max projection L2 error: `{_format_float(worst['max_projection_l2_error'])}`",
        f"- max force absolute error: `{_format_float(worst['max_force_abs_error'])}`",
        f"- max active mismatch count per state: `{worst['active_mismatch_count']}`",
        f"- max missing SDF sample count per state: `{worst['missing_sdf_sample_count']}`",
        "",
        "## Interpretation",
        "",
    ]
    if overall == "pass":
        lines.append(
            "For this block-plane trajectory, the triangulated dynamic-SDF plane query is numerically equivalent to the analytic plane query at the contact-sample level. Any remaining trajectory differences should be investigated in lifecycle ordering, Newton state history, or subsequent mechanics updates rather than basic SDF resolution."
        )
    else:
        lines.append(
            "The dynamic-SDF plane query is not sample-equivalent to the analytic plane query in this run. Inspect the detail CSV files for candidate misses, edge/vertex projections, normal differences, or active-set mismatches."
        )
    lines.extend(
        [
            "",
            "## Output Files",
            "",
            "- `sdf_plane_stateless_query_equivalence.csv`",
            "- `sdf_plane_persistent_lifecycle_equivalence.csv`",
            "- `sdf_plane_equivalence_summary.csv`",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=ROOT / "results" / "sdf_plane_equivalence")
    parser.add_argument("--duration", type=float, default=0.08)
    parser.add_argument("--dt", type=float, default=0.001)
    parser.add_argument("--resolution", type=int, default=1)
    parser.add_argument("--initial-velocity-z", type=float, default=-2.0)
    parser.add_argument("--stride", type=int, default=1)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    outputs = run_diagnostic(
        args.out_dir,
        duration=args.duration,
        dt=args.dt,
        resolution=args.resolution,
        initial_velocity_z=args.initial_velocity_z,
        stride=args.stride,
    )
    print("SDF plane equivalence diagnostic complete.")
    for name, path in outputs.items():
        print(f"{name}: {path}")


if __name__ == "__main__":
    main()
