"""Run Abaqus/Explicit flexible body free-fall cases onto a rigid plane.

Two validation-only commercial-solver cases are generated by default:

- a flexible C3D8R cube dropped onto a discrete rigid R3D4 plane,
- a flexible C3D4 sphere dropped onto the same rigid plane.

The generated artifacts live under the repository-root
``commercial_software_comparison`` directory and are not imported by the core
SFC package.
"""

from __future__ import annotations

import argparse
import csv
import math
import re
import shutil
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_DIR = ROOT / "commercial_software_comparison" / "abaqus_flexible_body_rigid_plane"
WALLCLOCK_RE = re.compile(r"WALLCLOCK TIME \(SEC\)\s*=\s*([0-9.]+)")
CASE_NAMES = ("cube_drop", "sphere_drop")


@dataclass(frozen=True)
class CommonConfig:
    density: float = 1200.0
    young: float = 5.0e7
    poisson: float = 0.30
    gravity: float = 9.81
    duration: float = 3.0
    output_interval: float = 0.001
    initial_gap: float = 0.02
    plane_half_width: float = 0.30


@dataclass(frozen=True)
class CubeConfig:
    side_length: float = 0.10
    cells_per_axis: int = 10


@dataclass(frozen=True)
class SphereConfig:
    radius: float = 0.05
    latitudes: int = 12
    longitudes: int = 24


def _chunked_lines(values: list[int], *, width: int = 16) -> list[str]:
    return [", ".join(str(value) for value in values[index : index + width]) for index in range(0, len(values), width)]


def _format_node(label: int, xyz: tuple[float, float, float]) -> str:
    return f"{label}, {xyz[0]:.12e}, {xyz[1]:.12e}, {xyz[2]:.12e}"


def _format_element(label: int, connectivity: tuple[int, ...]) -> str:
    return f"{label}, " + ", ".join(str(node) for node in connectivity)


def _cube_mesh(cfg: CubeConfig, common: CommonConfig) -> tuple[list[tuple[float, float, float]], list[tuple[int, ...]], list[int]]:
    n = cfg.cells_per_axis
    half = 0.5 * cfg.side_length
    bottom_z = common.initial_gap
    nodes: list[tuple[float, float, float]] = []
    node_id: dict[tuple[int, int, int], int] = {}
    for k in range(n + 1):
        z = bottom_z + cfg.side_length * k / n
        for j in range(n + 1):
            y = -half + cfg.side_length * j / n
            for i in range(n + 1):
                x = -half + cfg.side_length * i / n
                node_id[(i, j, k)] = len(nodes) + 1
                nodes.append((x, y, z))

    elements: list[tuple[int, ...]] = []
    for k in range(n):
        for j in range(n):
            for i in range(n):
                n000 = node_id[(i, j, k)]
                n100 = node_id[(i + 1, j, k)]
                n110 = node_id[(i + 1, j + 1, k)]
                n010 = node_id[(i, j + 1, k)]
                n001 = node_id[(i, j, k + 1)]
                n101 = node_id[(i + 1, j, k + 1)]
                n111 = node_id[(i + 1, j + 1, k + 1)]
                n011 = node_id[(i, j + 1, k + 1)]
                elements.append((n000, n100, n110, n010, n001, n101, n111, n011))
    return nodes, elements, list(range(1, len(nodes) + 1))


def _sphere_surface_nodes(cfg: SphereConfig, common: CommonConfig) -> tuple[list[tuple[float, float, float]], list[tuple[int, int, int]]]:
    if cfg.latitudes < 3:
        raise ValueError("sphere latitudes must be at least 3")
    if cfg.longitudes < 6:
        raise ValueError("sphere longitudes must be at least 6")

    center = (0.0, 0.0, common.initial_gap + cfg.radius)
    nodes: list[tuple[float, float, float]] = []
    rings: list[list[int]] = []
    top = len(nodes) + 1
    nodes.append((center[0], center[1], center[2] + cfg.radius))
    for latitude in range(1, cfg.latitudes):
        theta = math.pi * latitude / cfg.latitudes
        z = center[2] + cfg.radius * math.cos(theta)
        radial = cfg.radius * math.sin(theta)
        ring: list[int] = []
        for longitude in range(cfg.longitudes):
            phi = 2.0 * math.pi * longitude / cfg.longitudes
            ring.append(len(nodes) + 1)
            nodes.append((center[0] + radial * math.cos(phi), center[1] + radial * math.sin(phi), z))
        rings.append(ring)
    bottom = len(nodes) + 1
    nodes.append((center[0], center[1], center[2] - cfg.radius))

    triangles: list[tuple[int, int, int]] = []
    first_ring = rings[0]
    for j in range(cfg.longitudes):
        triangles.append((top, first_ring[(j + 1) % cfg.longitudes], first_ring[j]))
    for lower_index in range(len(rings) - 1):
        upper = rings[lower_index]
        lower = rings[lower_index + 1]
        for j in range(cfg.longitudes):
            a = upper[j]
            b = upper[(j + 1) % cfg.longitudes]
            c = lower[j]
            d = lower[(j + 1) % cfg.longitudes]
            triangles.append((a, b, d))
            triangles.append((a, d, c))
    last_ring = rings[-1]
    for j in range(cfg.longitudes):
        triangles.append((bottom, last_ring[j], last_ring[(j + 1) % cfg.longitudes]))
    return nodes, triangles


def _sub(a: tuple[float, float, float], b: tuple[float, float, float]) -> tuple[float, float, float]:
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _det3(a: tuple[float, float, float], b: tuple[float, float, float], c: tuple[float, float, float]) -> float:
    return (
        a[0] * (b[1] * c[2] - b[2] * c[1])
        - a[1] * (b[0] * c[2] - b[2] * c[0])
        + a[2] * (b[0] * c[1] - b[1] * c[0])
    )


def _sphere_mesh(cfg: SphereConfig, common: CommonConfig) -> tuple[list[tuple[float, float, float]], list[tuple[int, ...]], list[int]]:
    center = (0.0, 0.0, common.initial_gap + cfg.radius)
    surface_nodes, triangles = _sphere_surface_nodes(cfg, common)
    nodes = [center] + surface_nodes
    elements: list[tuple[int, ...]] = []
    for tri in triangles:
        a, b, c = (tri[0] + 1, tri[1] + 1, tri[2] + 1)
        va = _sub(nodes[a - 1], nodes[0])
        vb = _sub(nodes[b - 1], nodes[0])
        vc = _sub(nodes[c - 1], nodes[0])
        if _det3(va, vb, vc) < 0.0:
            b, c = c, b
        elements.append((1, a, b, c))
    return nodes, elements, list(range(1, len(nodes) + 1))


def _plane_part_lines(common: CommonConfig) -> list[str]:
    h = common.plane_half_width
    return [
        "*Part, name=RIGID_PLANE",
        "*Node",
        _format_node(1, (-h, -h, 0.0)),
        _format_node(2, (h, -h, 0.0)),
        _format_node(3, (h, h, 0.0)),
        _format_node(4, (-h, h, 0.0)),
        _format_node(5, (0.0, 0.0, 0.0)),
        "*Element, type=R3D4, elset=PLANE_EALL",
        "1, 1, 2, 3, 4",
        "*Nset, nset=PLANE_RP",
        "5",
        "*Rigid Body, ref node=PLANE_RP, elset=PLANE_EALL",
        "*End Part",
    ]


def _material_lines(common: CommonConfig) -> list[str]:
    return [
        "*Material, name=BODY_MAT",
        "*Density",
        f"{common.density:.12e}",
        "*Elastic",
        f"{common.young:.12e}, {common.poisson:.12e}",
        "*Surface Interaction, name=FRICTIONLESS_CONTACT",
        "*Surface Behavior, pressure-overclosure=HARD",
        "*Friction",
        "0.",
    ]


def build_input_text(case: str, common: CommonConfig | None = None) -> str:
    """Build an Abaqus input deck for one rigid-plane free-fall case."""

    common = common or CommonConfig()
    if case == "cube_drop":
        nodes, elements, all_nodes = _cube_mesh(CubeConfig(), common)
        part_name = "FLEX_CUBE"
        instance_name = "CUBE-1"
        element_type = "C3D8R"
        element_set = "CUBE_EALL"
        heading = "Commercial reference: flexible cube free fall onto rigid plane"
    elif case == "sphere_drop":
        nodes, elements, all_nodes = _sphere_mesh(SphereConfig(), common)
        part_name = "FLEX_SPHERE"
        instance_name = "SPHERE-1"
        element_type = "C3D4"
        element_set = "SPHERE_EALL"
        heading = "Commercial reference: flexible sphere free fall onto rigid plane"
    else:
        raise ValueError(f"unknown case {case!r}; expected one of {CASE_NAMES}")

    lines: list[str] = [
        "*Heading",
        heading,
        "*Preprint, echo=NO, model=NO, history=NO, contact=NO",
    ]
    lines.extend(_material_lines(common))
    lines.extend([f"*Part, name={part_name}", "*Node"])
    lines.extend(_format_node(label, xyz) for label, xyz in enumerate(nodes, start=1))
    lines.append(f"*Element, type={element_type}, elset={element_set}")
    lines.extend(_format_element(label, conn) for label, conn in enumerate(elements, start=1))
    lines.extend([f"*Elset, elset={element_set}, generate", f"1, {len(elements)}, 1", f"*Solid Section, elset={element_set}, material=BODY_MAT", ",", "*End Part"])
    lines.extend(_plane_part_lines(common))
    lines.extend(
        [
            "*Assembly, name=ASSEMBLY",
            f"*Instance, name={instance_name}, part={part_name}",
            "*End Instance",
            "*Instance, name=PLANE-1, part=RIGID_PLANE",
            "*End Instance",
            f"*Nset, nset=BODY_NODES, instance={instance_name}",
        ]
    )
    lines.extend(_chunked_lines(all_nodes))
    lines.extend(
        [
            "*End Assembly",
            "*Boundary",
            "PLANE-1.PLANE_RP, ENCASTRE",
            "*Step, name=FREE_FALL_CONTACT, nlgeom=YES",
            "*Dynamic, Explicit",
            f", {common.duration:.12e}",
            "*Bulk Viscosity",
            "0.06, 1.2",
            "*Dload",
            f"{instance_name}.{element_set}, GRAV, {common.gravity:.12e}, 0., 0., -1.",
            "*Contact",
            "*Contact Inclusions, ALL EXTERIOR",
            "*Contact Property Assignment",
            ", , FRICTIONLESS_CONTACT",
            f"*Output, field, time interval={common.output_interval:.12e}",
            "*Node Output",
            "U, V",
            "*Element Output, directions=YES",
            "S, LE",
            f"*Output, history, time interval={common.output_interval:.12e}",
            "*Energy Output",
            "ALLKE, ALLIE, ALLSE, ALLVD, ALLWK, ETOTAL",
            "*End Step",
            "",
        ]
    )
    return "\n".join(lines)


def _resolve_abaqus_command(command: str | None) -> str:
    if command:
        return command
    for candidate in ("abaqus", "abq2024"):
        resolved = shutil.which(candidate)
        if resolved:
            return resolved
    raise RuntimeError("Abaqus command not found; pass --abaqus-command with the local launcher path")


def _run_command(command: list[str], *, cwd: Path, log_path: Path) -> float:
    start = time.perf_counter()
    result = subprocess.run(command, cwd=cwd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)
    elapsed = time.perf_counter() - start
    log_path.write_text(result.stdout, encoding="utf-8")
    print(result.stdout)
    if result.returncode != 0:
        raise RuntimeError(f"command failed with exit code {result.returncode}: {' '.join(command)}")
    return elapsed


def _abaqus_reported_wallclock_seconds(sta_path: Path) -> float | None:
    if not sta_path.exists():
        return None
    matches = WALLCLOCK_RE.findall(sta_path.read_text(encoding="utf-8", errors="ignore"))
    if not matches:
        return None
    return float(matches[-1])


def _mesh_counts(case: str, common: CommonConfig) -> tuple[int, int]:
    if case == "cube_drop":
        nodes, elements, _ = _cube_mesh(CubeConfig(), common)
    elif case == "sphere_drop":
        nodes, elements, _ = _sphere_mesh(SphereConfig(), common)
    else:
        raise ValueError(case)
    return len(nodes) + 5, len(elements) + 1


def _write_case_metrics(path: Path, rows: dict[str, str | int | float]) -> None:
    with path.open("w", encoding="ascii", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["metric", "value"])
        for key, value in rows.items():
            writer.writerow([key, value])


def run_case(case: str, out_root: Path, *, abaqus_command: str | None = None) -> dict[str, Path | int | float | str]:
    common = CommonConfig()
    total_start = time.perf_counter()
    case_dir = out_root / case
    run_dir = case_dir / "abaqus_run"
    vtk_dir = case_dir / "vtk"
    run_dir.mkdir(parents=True, exist_ok=True)
    vtk_dir.mkdir(parents=True, exist_ok=True)

    job_name = f"{case}_explicit"
    inp_path = run_dir / f"{job_name}.inp"
    inp_path.write_text(build_input_text(case, common), encoding="ascii")
    node_count, element_count = _mesh_counts(case, common)

    command = _resolve_abaqus_command(abaqus_command)
    analysis_wall_seconds = _run_command(
        [command, f"job={job_name}", f"input={inp_path.name}", "interactive", "ask_delete=OFF"],
        cwd=run_dir,
        log_path=case_dir / "abaqus_analysis_stdout.log",
    )
    odb_path = run_dir / f"{job_name}.odb"
    if not odb_path.exists():
        raise RuntimeError(f"Abaqus completed without producing {odb_path}")

    converter = Path(__file__).with_name("abaqus_odb_to_vtk.py")
    export_wall_seconds = _run_command(
        [command, "python", str(converter), "--odb", str(odb_path), "--out-dir", str(vtk_dir), "--stem", "frame"],
        cwd=run_dir,
        log_path=case_dir / "abaqus_odb_to_vtk_stdout.log",
    )
    frame_count = len(sorted(vtk_dir.glob("frame_*.vtk")))
    if frame_count == 0:
        raise RuntimeError(f"ODB export produced no VTK frames in {vtk_dir}")
    total_wall_seconds = time.perf_counter() - total_start
    abaqus_reported_wall = _abaqus_reported_wallclock_seconds(run_dir / f"{job_name}.sta")
    metrics_path = case_dir / "runtime_metrics.csv"
    _write_case_metrics(
        metrics_path,
        {
            "case": case,
            "abaqus_analysis_wall_seconds": f"{analysis_wall_seconds:.6f}",
            "abaqus_reported_explicit_wallclock_seconds": f"{abaqus_reported_wall:.6f}" if abaqus_reported_wall is not None else "",
            "odb_to_vtk_wall_seconds": f"{export_wall_seconds:.6f}",
            "total_workflow_wall_seconds": f"{total_wall_seconds:.6f}",
            "abaqus_model_duration_seconds": f"{common.duration:.6f}",
            "field_output_interval_seconds": f"{common.output_interval:.6f}",
            "vtk_frame_count": frame_count,
            "node_count_per_frame": node_count,
            "element_count_per_frame": element_count,
            "material_density": f"{common.density:.6f}",
            "material_young": f"{common.young:.6f}",
            "material_poisson": f"{common.poisson:.6f}",
        },
    )
    (case_dir / "README.md").write_text(
        "\n".join(
            [
                f"# Abaqus {case} Flexible-Body Rigid-Plane Reference",
                "",
                "Commercial-solver comparison artifact generated by a validation-only workflow.",
                "",
                f"- Input deck: `{inp_path.relative_to(case_dir).as_posix()}`",
                f"- ODB: `{odb_path.relative_to(case_dir).as_posix()}`",
                "- Requested field output: `U`, `V`, `S`, `LE`.",
                f"- ParaView collection: `{(vtk_dir / 'frame.pvd').relative_to(case_dir).as_posix()}`",
                f"- Numbered VTK frames: `{frame_count}` files named `frame_0000.vtk`, `frame_0001.vtk`, ...",
                f"- Runtime metrics: `{metrics_path.relative_to(case_dir).as_posix()}`",
                f"- Abaqus analysis wall time: `{analysis_wall_seconds:.3f}` s.",
                f"- Abaqus-reported Explicit wallclock time: `{abaqus_reported_wall:.3f}` s." if abaqus_reported_wall is not None else "- Abaqus-reported Explicit wallclock time: unavailable.",
                f"- ODB-to-VTK wall time: `{export_wall_seconds:.3f}` s.",
                f"- Total workflow wall time: `{total_wall_seconds:.3f}` s.",
                "",
                "Object ids in VTK cell data: `0` = rigid plane, `1` = cube, `2` = sphere.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return {
        "case": case,
        "case_dir": case_dir,
        "inp": inp_path,
        "odb": odb_path,
        "pvd": vtk_dir / "frame.pvd",
        "frame_count": frame_count,
        "metrics": metrics_path,
        "analysis_wall_seconds": analysis_wall_seconds,
        "export_wall_seconds": export_wall_seconds,
        "total_wall_seconds": total_wall_seconds,
    }


def _write_summary(out_root: Path, results: list[dict[str, Path | int | float | str]]) -> None:
    summary_csv = out_root / "summary.csv"
    with summary_csv.open("w", encoding="ascii", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["case", "frame_count", "pvd", "metrics", "analysis_wall_seconds", "export_wall_seconds", "total_wall_seconds"],
        )
        writer.writeheader()
        for result in results:
            writer.writerow(
                {
                    "case": result["case"],
                    "frame_count": result["frame_count"],
                    "pvd": Path(result["pvd"]).relative_to(out_root).as_posix(),
                    "metrics": Path(result["metrics"]).relative_to(out_root).as_posix(),
                    "analysis_wall_seconds": f"{float(result['analysis_wall_seconds']):.6f}",
                    "export_wall_seconds": f"{float(result['export_wall_seconds']):.6f}",
                    "total_wall_seconds": f"{float(result['total_wall_seconds']):.6f}",
                }
            )
    (out_root / "README.md").write_text(
        "\n".join(
            [
                "# Abaqus Flexible Body Free-Fall To Rigid Plane",
                "",
                "Two Abaqus/Explicit commercial-solver comparison cases.",
                "",
                "- Duration: `3.0 s`.",
                "- Field output interval: `0.001 s`.",
                "- Contact: frictionless general contact against a discrete rigid R3D4 plane.",
                "- Outputs: `U`, `V`, `S`, `LE`, numbered legacy VTK frames, and PVD collections.",
                f"- Summary CSV: `{summary_csv.name}`",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--abaqus-command", default=None)
    parser.add_argument("--case", choices=CASE_NAMES, action="append", help="Run one case; repeat to run multiple. Defaults to both.")
    args = parser.parse_args()

    cases = args.case or list(CASE_NAMES)
    results = [run_case(case, args.out_dir, abaqus_command=args.abaqus_command) for case in cases]
    _write_summary(args.out_dir, results)
    for result in results:
        print(f"{result['case']}: {result['pvd']} ({result['frame_count']} frames)")


if __name__ == "__main__":
    main()
