"""CalculiX explicit linear-contact comparison for the undamped sphere drop.

This validation-only runner starts from the no-contact-damping Abaqus/Explicit
input/VTK results generated by
``run_abaqus_explicit_linear_timestep_convergence.py`` and writes an equivalent
CalculiX ``*DYNAMIC,DIRECT,EXPLICIT`` model with frictionless linear penalty
contact.  CalculiX is used only as an external reference solver; it is not part
of SFC core assembly, time integration, or contact evaluation.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from time import perf_counter
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from validation.run_abaqus_sphere_drop_full_validation import _abaqus_history_from_vtk  # noqa: E402
from validation.run_abaqus_sphere_drop_short_validation import (  # noqa: E402
    _configure_plot_style,
    parse_sphere_drop_inp,
)
from validation.run_calculix_drop_impact_comparison import (  # noqa: E402
    _fieldnames,
    _parse_calculix_dat_contact_totals,
    _parse_calculix_dat_displacements,
    _write_csv,
    run_calculix,
)
from validation.run_calculix_same_sphere_drop_comparison import (  # noqa: E402
    _calculix_history_from_displacements,
    _comparison_metrics,
    build_calculix_model_from_abaqus,
)

Row = dict[str, Any]

DEFAULT_ABAQUS_ROOT = ROOT / "results" / "abaqus_explicit_linear_no_contact_damping_fine_1s"
DEFAULT_REFERENCE_CASE = "dt_5em06"
DEFAULT_INP = DEFAULT_ABAQUS_ROOT / DEFAULT_REFERENCE_CASE / "abaqus_run" / "sphere_drop_explicit_linear_dt_5em06.inp"
DEFAULT_VTK_DIR = DEFAULT_ABAQUS_ROOT / DEFAULT_REFERENCE_CASE / "vtk"
DEFAULT_OUT_DIR = ROOT / "results" / "calculix_explicit_linear_sphere_drop_comparison"


def _write_rows(path: Path, rows: list[Row]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    _write_csv(path, _fieldnames(rows), rows)


def _read_rows(path: Path) -> list[Row]:
    with path.open(newline="", encoding="utf-8") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def _case_metric(path: Path, case: str) -> Row | None:
    if not path.is_file():
        return None
    for row in _read_rows(path):
        if row.get("case") == case:
            return row
    return None


def _filter_duration(rows: list[Row], duration: float) -> list[Row]:
    return [row for row in rows if float(row["time"]) <= float(duration) + 1.0e-12]


def _series(rows: list[Row], key: str) -> tuple[np.ndarray, np.ndarray]:
    values = [row for row in rows if key in row and row[key] != ""]
    return (
        np.asarray([float(row["time"]) for row in values], dtype=float),
        np.asarray([float(row[key]) for row in values], dtype=float),
    )


def _plot_overlay(path: Path, source_rows: dict[str, list[Row]], *, key: str, ylabel: str, title: str) -> None:
    _configure_plot_style()
    styles = {
        "abaqus_explicit_vtk": ("#1f4e79", "-", "Abaqus/Explicit"),
        "calculix_explicit_ccx": ("#548235", "--", "CalculiX explicit"),
    }
    fig, ax = plt.subplots(figsize=(3.35, 2.2), constrained_layout=True)
    for source, rows in source_rows.items():
        t, y = _series(rows, key)
        if t.size == 0:
            continue
        color, linestyle, label = styles.get(source, ("#666666", "-", source))
        ax.plot(t, y, color=color, linestyle=linestyle, linewidth=1.45, label=label)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(True, color="#d9d9d9", linewidth=0.5)
    ax.legend(loc="best", frameon=True)
    fig.savefig(path, dpi=300)
    fig.savefig(path.with_suffix(".pdf"))
    plt.close(fig)


def _rename_sources(rows: list[Row], source: str, contact_path: str) -> list[Row]:
    renamed: list[Row] = []
    for row in rows:
        next_row = dict(row)
        next_row["source"] = source
        next_row["contact_path"] = contact_path
        renamed.append(next_row)
    return renamed


def _timing_rows(*, calculix_wall: float, abaqus_case_row: Row | None, case_name: str) -> list[Row]:
    rows: list[Row] = [
        {
            "source": "calculix_explicit_ccx",
            "case": case_name,
            "metric": "native_solve_wall_seconds",
            "value": float(calculix_wall),
            "scope": "ccx solve plus DAT writing measured by runner",
        }
    ]
    if abaqus_case_row is not None:
        rows.extend(
            [
                {
                    "source": "abaqus_explicit",
                    "case": case_name,
                    "metric": "analysis_wall_seconds",
                    "value": float(abaqus_case_row["analysis_wall_seconds"]),
                    "scope": "Abaqus analysis only",
                },
                {
                    "source": "abaqus_explicit",
                    "case": case_name,
                    "metric": "total_wall_seconds",
                    "value": float(abaqus_case_row["total_wall_seconds"]),
                    "scope": "Abaqus analysis plus VTK and energy extraction",
                },
            ]
        )
    return rows


def _write_summary(
    path: Path,
    *,
    duration: float,
    dt: float,
    outputs: dict[str, Path],
    metrics: list[Row],
    timing: list[Row],
) -> None:
    lines = [
        "# CalculiX Explicit Linear Sphere-Drop Comparison",
        "",
        "本验证把同一个无摩擦、无接触阻尼、线性 penalty 小球跌落刚性平面工况写成 CalculiX `*DYNAMIC,DIRECT,EXPLICIT`。",
        "Abaqus/Explicit 的 VTK 结果只作为外部参考曲线；CalculiX 也只作为外部开源求解器对照，不进入 SFC core。",
        "",
        "## Setup",
        "",
        f"- Duration: `{duration:.6g} s`.",
        f"- Fixed explicit time increment: `{dt:.6g} s`.",
        "- Contact: frictionless linear pressure-overclosure penalty; CalculiX friction card is omitted because ccx rejects a zero friction coefficient.",
        "- Damping: no material damping card; no contact damping card is written in the CalculiX deck.",
        "",
        "## Accuracy Metrics",
        "",
        "| Source | Metric | Value |",
        "| --- | --- | ---: |",
    ]
    for row in metrics:
        lines.append(f"| `{row['source']}` | `{row['metric']}` | {row['value']} |")
    lines.extend(["", "## Timing", "", "| Source | Metric | Value (s) | Scope |", "| --- | --- | ---: | --- |"])
    for row in timing:
        lines.append(f"| `{row['source']}` | `{row['metric']}` | {row['value']} | {row['scope']} |")
    lines.extend(["", "## Outputs", ""])
    for key, value in outputs.items():
        lines.append(f"- `{key}`: `{value.name}`")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_validation(
    out_dir: Path,
    *,
    inp: Path = DEFAULT_INP,
    vtk_dir: Path = DEFAULT_VTK_DIR,
    duration: float = 1.0,
    dt: float = 5.0e-6,
    output_interval: float = 0.001,
    calculix_timeout_seconds: int = 1200,
) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    source = parse_sphere_drop_inp(inp)
    duration_value = min(float(duration), float(source.abaqus_duration))
    output_frequency = max(1, int(round(float(output_interval) / float(dt))))
    model = build_calculix_model_from_abaqus(
        source,
        duration=duration_value,
        dt=float(dt),
        hht_alpha=0.0,
        output_frequency=output_frequency,
        direct_dynamic=True,
        explicit_dynamic=True,
        friction_coefficient=0.0,
    )
    model.case = "calculix_explicit_linear_sphere_drop"
    model.model_source = "abaqus_explicit_linear_no_contact_damping_inp"

    start = perf_counter()
    dat_path, command_row = run_calculix(
        model,
        out_dir,
        case_name=f"calculix_explicit_linear_dt_{dt:.0e}".replace("-", "m"),
        timeout_seconds=int(calculix_timeout_seconds),
    )
    calculix_wall = perf_counter() - start

    blocks = _parse_calculix_dat_displacements(dat_path, model.node_ids)
    totals = _parse_calculix_dat_contact_totals(dat_path)
    calculix_rows = _rename_sources(
        _filter_duration(_calculix_history_from_displacements(model, blocks, totals), duration_value),
        "calculix_explicit_ccx",
        "CalculiX *DYNAMIC,DIRECT,EXPLICIT surface-to-surface linear penalty contact",
    )
    abaqus_rows = _rename_sources(
        _filter_duration(_abaqus_history_from_vtk(source, vtk_dir, duration=duration_value), duration_value),
        "abaqus_explicit_vtk",
        "Abaqus/Explicit no-contact-damping native contact VTK replay",
    )
    source_rows = {
        "abaqus_explicit_vtk": abaqus_rows,
        "calculix_explicit_ccx": calculix_rows,
    }
    metrics = _comparison_metrics(source_rows, reference_name="abaqus_explicit_vtk")
    case_name = Path(vtk_dir).parent.name
    abaqus_case_row = _case_metric(DEFAULT_ABAQUS_ROOT / "abaqus_explicit_linear_case_metrics.csv", case_name)
    timing = _timing_rows(calculix_wall=calculix_wall, abaqus_case_row=abaqus_case_row, case_name=case_name)
    command_row.update(
        {
            "calculix_wall_seconds_measured_by_runner": float(calculix_wall),
            "dynamic_procedure": "*DYNAMIC,DIRECT,EXPLICIT",
            "fixed_dt": float(dt),
            "output_frequency": output_frequency,
            "friction_coefficient": 0.0,
        }
    )

    outputs = {
        "calculix_history": out_dir / "calculix_explicit_linear_history.csv",
        "abaqus_history": out_dir / "abaqus_explicit_linear_reference_history.csv",
        "metrics": out_dir / "calculix_explicit_linear_metrics.csv",
        "timing": out_dir / "calculix_explicit_linear_timing.csv",
        "command": out_dir / "calculix_explicit_linear_command.csv",
        "z_cm_curve": out_dir / "calculix_explicit_linear_z_cm.png",
        "gap_curve": out_dir / "calculix_explicit_linear_min_gap.png",
        "force_curve": out_dir / "calculix_explicit_linear_normal_force.png",
        "summary": out_dir / "calculix_explicit_linear_summary_cn.md",
    }
    _write_rows(outputs["calculix_history"], calculix_rows)
    _write_rows(outputs["abaqus_history"], abaqus_rows)
    _write_rows(outputs["metrics"], metrics)
    _write_rows(outputs["timing"], timing)
    _write_rows(outputs["command"], [command_row])
    _plot_overlay(outputs["z_cm_curve"], source_rows, key="z_cm", ylabel="Mass-center z (m)", title="Undamped explicit displacement")
    _plot_overlay(outputs["gap_curve"], source_rows, key="min_gap", ylabel="Minimum gap (m)", title="Undamped explicit minimum gap")
    _plot_overlay(outputs["force_curve"], source_rows, key="normal_force_z", ylabel="Normal contact force (N)", title="Undamped explicit contact force")
    _write_summary(outputs["summary"], duration=duration_value, dt=float(dt), outputs=outputs, metrics=metrics, timing=timing)
    return outputs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inp", type=Path, default=DEFAULT_INP)
    parser.add_argument("--vtk-dir", type=Path, default=DEFAULT_VTK_DIR)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--duration", type=float, default=1.0)
    parser.add_argument("--dt", type=float, default=5.0e-6)
    parser.add_argument("--output-interval", type=float, default=0.001)
    parser.add_argument("--calculix-timeout-seconds", type=int, default=1200)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    outputs = run_validation(
        args.out_dir,
        inp=args.inp,
        vtk_dir=args.vtk_dir,
        duration=float(args.duration),
        dt=float(args.dt),
        output_interval=float(args.output_interval),
        calculix_timeout_seconds=int(args.calculix_timeout_seconds),
    )
    print("CalculiX explicit linear sphere-drop comparison complete.")
    for key, value in outputs.items():
        print(f"{key}: {value}")


if __name__ == "__main__":
    main()
